# Generated by Django 3.2.9 on 2021-11-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211125_2225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passenger',
            table='passenger_tbl',
        ),
    ]
