# Generated by Django 3.2.9 on 2021-11-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_passenger_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='url_image',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
